### PR TITLE
api for task counter for reward page

### PR DESCRIPTION
**Pull request by RaunakSharma002**
### Functionality:
api for CompletedTask counter for reward page

### Solution:
make an api

## WtId:
Dev 661

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
by mark task as completed

### CODE REVIEW

**Comment by sanjaykrishna1203** [comment]
How does an organizations's tasks or tasks completed by a user for an organization reflect in the overall profile of the user? discussion needed...

**Review by viv9k — APPROVED** [review]
Approved

**Review by viv9k — COMMENTED** [review]
But this change should go to a separate branch marked rewards system

**Comment by simran142002** [comment]
I have created a branch reward system you can try changing the base branch to that

**Review by viv9k — APPROVED** [review]
Approved

**Comment by sanjaykrishna1203** [comment]
@RaunakSharma002 change the base to [dev-rewards](https://github.com/Worktez/worktez/tree/dev-rewards)

**Comment by simran142002** [comment]
Please resolve the merge conflict

**Comment by RaunakSharma002** [comment]
raised another PR instead of this

**Pull request closed without merging**
