### PR TITLE
Fix/pop up

### PR DESCRIPTION
**Pull request by simran142002**
### Functionality:
fixed create new task pop up bug

### Solution:
made changes in create new task ts

### Risk level:
- [ ] high 
- [ ] medium
- [X] low

### How to test:
ng serve -o
firebase emulators:start

### CODE REVIEW

**Review by viv9k — CHANGES_REQUESTED** [review]
This PR has lot of unnecessary changes and can be improved a lot. Please have a clean PR for this.

**Review by Pendyala-thanvi — COMMENTED** [review]
Resolve merge conflicts

**Review by viv9k — APPROVED** [review]
Approved

**Review by Pendyala-thanvi — COMMENTED** [review]
resolve merge conflicts

**Pull request closed without merging**
