### PR TITLE
feat/openFiles: open files upon click in task details and my organisations document section

### PR DESCRIPTION
**Pull request by akanksha3012**
### Functionality:
feat/openFiles

### Solution:
open files in new tab upon click in Task details and My Organisation documents section.

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
1. firebase emulators:start
2. ng serve
3. auto setup
4. go to my organisations document section. Upload a file if not one is uploaded.
5. click on the document icon of the respective file to view it. The file opens in a new tab.

### CODE REVIEW

**Comment by viv9k** [comment]
Please give demo on this

**Review by viv9k — APPROVED** [review]
Approved

**Review by viv9k — APPROVED** [review]
Approved

**Review by Pendyala-thanvi — APPROVED** [review]
Approved

**Pull request merged**
